CREATE TABLE IF NOT EXISTS TWITHDRAWALS(
    DFORDER BIGINT NOT NULL UNIQUE,
    DFUSER INTEGER NOT NULL,
    DFWITHDRAW INT,
    DFCREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_WITHDRAWALS_ORDER on TWITHDRAWALS(DFORDER);
CREATE INDEX IDX_WITHDRAWALS_USER on TORDERS(DFUSER);