CREATE TABLE IF NOT EXISTS TUSERS (
DFUSER SERIAL PRIMARY KEY,
DFLOGIN VARCHAR(255) NOT NULL UNIQUE,
DFPASSWORD VARCHAR(255) NOT NULL,
DFCREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_USERS_LOGIN ON TUSERS(DFUSER);
