CREATE TABLE IF NOT EXISTS TORDERS(
    DFORDER BIGINT NOT NULL UNIQUE,
    DFUSER INTEGER NOT NULL,
    DFSTATUS VARCHAR(255) NOT NULL,
    DFACCRUAL INTEGER,
    DFCREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DFUPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_ORDERS_ORDER on TORDERS(DFORDER);
CREATE INDEX IDX_ORDERS_USER on TORDERS(DFUSER);