// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/qesterrx/gofermart/internal/model"
	mock "github.com/stretchr/testify/mock"

	status "github.com/qesterrx/gofermart/internal/status"
)

// AccrualStorage is an autogenerated mock type for the AccrualStorage type
type AccrualStorage struct {
	mock.Mock
}

// GetOrdersWOaccrual provides a mock function with given fields: limit
func (_m *AccrualStorage) GetOrdersWOaccrual(limit int) (*[]model.DBOrder, status.Status) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersWOaccrual")
	}

	var r0 *[]model.DBOrder
	var r1 status.Status
	if rf, ok := ret.Get(0).(func(int) (*[]model.DBOrder, status.Status)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) *[]model.DBOrder); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.DBOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(int) status.Status); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Get(1).(status.Status)
	}

	return r0, r1
}

// UpdateOrder provides a mock function with given fields: order
func (_m *AccrualStorage) UpdateOrder(order *model.DBOrder) status.Status {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 status.Status
	if rf, ok := ret.Get(0).(func(*model.DBOrder) status.Status); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Get(0).(status.Status)
	}

	return r0
}

// NewAccrualStorage creates a new instance of AccrualStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccrualStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccrualStorage {
	mock := &AccrualStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
