// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/qesterrx/gofermart/internal/model"
	mock "github.com/stretchr/testify/mock"

	status "github.com/qesterrx/gofermart/internal/status"
)

// GofermartService is an autogenerated mock type for the GofermartService type
type GofermartService struct {
	mock.Mock
}

// CheckOrderNumber provides a mock function with given fields: order
func (_m *GofermartService) CheckOrderNumber(order string) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for CheckOrderNumber")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalance provides a mock function with given fields: user
func (_m *GofermartService) GetBalance(user int) (model.Balance, status.Status) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 model.Balance
	var r1 status.Status
	if rf, ok := ret.Get(0).(func(int) (model.Balance, status.Status)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(int) model.Balance); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(model.Balance)
	}

	if rf, ok := ret.Get(1).(func(int) status.Status); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(status.Status)
	}

	return r0, r1
}

// GetOrders provides a mock function with given fields: user
func (_m *GofermartService) GetOrders(user int) ([]model.Order, status.Status) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []model.Order
	var r1 status.Status
	if rf, ok := ret.Get(0).(func(int) ([]model.Order, status.Status)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(int) []model.Order); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(int) status.Status); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(status.Status)
	}

	return r0, r1
}

// GetWithdrawals provides a mock function with given fields: user
func (_m *GofermartService) GetWithdrawals(user int) ([]model.Withdraw, status.Status) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []model.Withdraw
	var r1 status.Status
	if rf, ok := ret.Get(0).(func(int) ([]model.Withdraw, status.Status)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(int) []model.Withdraw); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdraw)
		}
	}

	if rf, ok := ret.Get(1).(func(int) status.Status); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(status.Status)
	}

	return r0, r1
}

// Login provides a mock function with given fields: login, password
func (_m *GofermartService) Login(login string, password string) (string, status.Status) {
	ret := _m.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 status.Status
	if rf, ok := ret.Get(0).(func(string, string) (string, status.Status)); ok {
		return rf(login, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(login, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) status.Status); ok {
		r1 = rf(login, password)
	} else {
		r1 = ret.Get(1).(status.Status)
	}

	return r0, r1
}

// NewOrder provides a mock function with given fields: user, order
func (_m *GofermartService) NewOrder(user int, order string) status.Status {
	ret := _m.Called(user, order)

	if len(ret) == 0 {
		panic("no return value specified for NewOrder")
	}

	var r0 status.Status
	if rf, ok := ret.Get(0).(func(int, string) status.Status); ok {
		r0 = rf(user, order)
	} else {
		r0 = ret.Get(0).(status.Status)
	}

	return r0
}

// NewWithdraw provides a mock function with given fields: user, wd
func (_m *GofermartService) NewWithdraw(user int, wd *model.NewWithdraw) status.Status {
	ret := _m.Called(user, wd)

	if len(ret) == 0 {
		panic("no return value specified for NewWithdraw")
	}

	var r0 status.Status
	if rf, ok := ret.Get(0).(func(int, *model.NewWithdraw) status.Status); ok {
		r0 = rf(user, wd)
	} else {
		r0 = ret.Get(0).(status.Status)
	}

	return r0
}

// Register provides a mock function with given fields: login, password
func (_m *GofermartService) Register(login string, password string) status.Status {
	ret := _m.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 status.Status
	if rf, ok := ret.Get(0).(func(string, string) status.Status); ok {
		r0 = rf(login, password)
	} else {
		r0 = ret.Get(0).(status.Status)
	}

	return r0
}

// NewGofermartService creates a new instance of GofermartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGofermartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GofermartService {
	mock := &GofermartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
