// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/qesterrx/gofermart/internal/model"
	mock "github.com/stretchr/testify/mock"

	status "github.com/qesterrx/gofermart/internal/status"
)

// GofermartStorage is an autogenerated mock type for the GofermartStorage type
type GofermartStorage struct {
	mock.Mock
}

// CheckOrderExist provides a mock function with given fields: order, user
func (_m *GofermartStorage) CheckOrderExist(order int, user int) status.Status {
	ret := _m.Called(order, user)

	if len(ret) == 0 {
		panic("no return value specified for CheckOrderExist")
	}

	var r0 status.Status
	if rf, ok := ret.Get(0).(func(int, int) status.Status); ok {
		r0 = rf(order, user)
	} else {
		r0 = ret.Get(0).(status.Status)
	}

	return r0
}

// GetBalance provides a mock function with given fields: user
func (_m *GofermartStorage) GetBalance(user int) (int, int, status.Status) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 int
	var r1 int
	var r2 status.Status
	if rf, ok := ret.Get(0).(func(int) (int, int, status.Status)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) int); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int) status.Status); ok {
		r2 = rf(user)
	} else {
		r2 = ret.Get(2).(status.Status)
	}

	return r0, r1, r2
}

// GetOrders provides a mock function with given fields: user
func (_m *GofermartStorage) GetOrders(user int) (*[]model.DBOrder, status.Status) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 *[]model.DBOrder
	var r1 status.Status
	if rf, ok := ret.Get(0).(func(int) (*[]model.DBOrder, status.Status)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(int) *[]model.DBOrder); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.DBOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(int) status.Status); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(status.Status)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: login
func (_m *GofermartStorage) GetUser(login string) (*model.DBUser, status.Status) {
	ret := _m.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *model.DBUser
	var r1 status.Status
	if rf, ok := ret.Get(0).(func(string) (*model.DBUser, status.Status)); ok {
		return rf(login)
	}
	if rf, ok := ret.Get(0).(func(string) *model.DBUser); ok {
		r0 = rf(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DBUser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) status.Status); ok {
		r1 = rf(login)
	} else {
		r1 = ret.Get(1).(status.Status)
	}

	return r0, r1
}

// GetWithdrawals provides a mock function with given fields: user
func (_m *GofermartStorage) GetWithdrawals(user int) (*[]model.DBWithdraw, status.Status) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 *[]model.DBWithdraw
	var r1 status.Status
	if rf, ok := ret.Get(0).(func(int) (*[]model.DBWithdraw, status.Status)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(int) *[]model.DBWithdraw); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.DBWithdraw)
		}
	}

	if rf, ok := ret.Get(1).(func(int) status.Status); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(status.Status)
	}

	return r0, r1
}

// NewOrder provides a mock function with given fields: order
func (_m *GofermartStorage) NewOrder(order *model.DBOrder) status.Status {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for NewOrder")
	}

	var r0 status.Status
	if rf, ok := ret.Get(0).(func(*model.DBOrder) status.Status); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Get(0).(status.Status)
	}

	return r0
}

// NewUser provides a mock function with given fields: login, password
func (_m *GofermartStorage) NewUser(login string, password string) status.Status {
	ret := _m.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for NewUser")
	}

	var r0 status.Status
	if rf, ok := ret.Get(0).(func(string, string) status.Status); ok {
		r0 = rf(login, password)
	} else {
		r0 = ret.Get(0).(status.Status)
	}

	return r0
}

// NewWithdraw provides a mock function with given fields: withdraw
func (_m *GofermartStorage) NewWithdraw(withdraw *model.DBWithdraw) status.Status {
	ret := _m.Called(withdraw)

	if len(ret) == 0 {
		panic("no return value specified for NewWithdraw")
	}

	var r0 status.Status
	if rf, ok := ret.Get(0).(func(*model.DBWithdraw) status.Status); ok {
		r0 = rf(withdraw)
	} else {
		r0 = ret.Get(0).(status.Status)
	}

	return r0
}

// NewGofermartStorage creates a new instance of GofermartStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGofermartStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *GofermartStorage {
	mock := &GofermartStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
